# Generated by Django 4.2.1 on 2023-05-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0002_archive_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "scheduled"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                ],
                db_index=True,
                default="scheduled",
                max_length=255,
            ),
        ),
    ]
