# Generated by Django 4.2.1 on 2023-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0003_alter_archive_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="frequency",
            field=models.PositiveIntegerField(default=1800),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="last_archived_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="archive",
            name="source",
            field=models.ImageField(
                blank=True,
                help_text="store the image of the resource",
                null=True,
                upload_to="media/archive/",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
