# Generated by Django 4.2.1 on 2023-05-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0004_resource_frequency_resource_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("1 minute", "1 minute"),
                    ("30 minutes", "30 minutes"),
                    ("1 hour", "1 hour"),
                    ("3 hour", "3 hour"),
                    ("6 hour", "6 hour"),
                    ("12 hour", "12 hour"),
                    ("18 hour", "18 hour"),
                    ("1 day", "1 day"),
                    ("1 week", "1 week"),
                    ("1 month", "1 month"),
                    ("3 month", "3 month"),
                    ("6 month", "6 month"),
                    ("12 month", "12 month"),
                ],
                default="1 min",
                max_length=255,
            ),
        ),
    ]
