# Generated by Django 4.2.1 on 2023-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0005_alter_resource_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="frequency",
            field=models.PositiveIntegerField(
                choices=[
                    (15, "15 seconds"),
                    (60, "1 minute"),
                    (180, "3 minutes"),
                    (1800, "30 minutes"),
                    (6000, "1 hour"),
                ],
                default=60,
            ),
        ),
    ]
